"""change

Revision ID: 4a3b2f24e740
Revises: 4c8739eee700
Create Date: 2024-10-06 19:42:03.004507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a3b2f24e740'
down_revision: Union[str, None] = '4c8739eee700'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('datetime_local', sa.DateTime(), nullable=False))
    op.add_column('images', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('images', sa.Column('datetime_utc', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('images', 'datetime')
    op.drop_column('images', 'timezone_known')
    op.drop_column('images', 'gps_datetime')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('gps_datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('images', sa.Column('timezone_known', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('images', sa.Column('datetime', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('images', 'datetime_utc')
    op.drop_column('images', 'timezone')
    op.drop_column('images', 'datetime_local')
    # ### end Alembic commands ###
