"""Remove thumbnails

Revision ID: 55d2ee8631e2
Revises: de5472a74464
Create Date: 2024-10-01 22:21:24.968023

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55d2ee8631e2"
down_revision: Union[str, None] = "de5472a74464"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thumbnails")
    op.alter_column(
        "images",
        "id",
        existing_type=sa.UUID(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.drop_column("images", "hash")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images", sa.Column("hash", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.alter_column(
        "images",
        "id",
        existing_type=sa.String(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.create_table(
        "thumbnails",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("image_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("width", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("height", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("size", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["image_id"], ["images.id"], name="thumbnails_image_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="thumbnails_pkey"),
    )
    # ### end Alembic commands ###
