"""change

Revision ID: 6ee654e09e2b
Revises: 4a3b2f24e740
Create Date: 2024-10-06 20:12:57.075192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6ee654e09e2b"
down_revision: Union[str, None] = "4a3b2f24e740"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("timezone_name", sa.String(), nullable=True))
    op.add_column("images", sa.Column("timezone_offset", sa.Interval(), nullable=True))
    op.drop_column("images", "timezone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "images",
        sa.Column("timezone", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("images", "timezone_offset")
    op.drop_column("images", "timezone_name")
    # ### end Alembic commands ###
