"""add time and gps

Revision ID: d6e8af1c2fb5
Revises: 6ca122218981
Create Date: 2024-10-05 21:49:19.350702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e8af1c2fb5'
down_revision: Union[str, None] = '6ca122218981'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('province', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_locations_id'), 'geo_locations', ['id'], unique=False)
    op.add_column('images', sa.Column('datetime_taken', sa.DateTime(timezone=True), nullable=False))
    op.add_column('images', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('altitude', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'geo_locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'location_id')
    op.drop_column('images', 'altitude')
    op.drop_column('images', 'longitude')
    op.drop_column('images', 'latitude')
    op.drop_column('images', 'datetime_taken')
    op.drop_index(op.f('ix_geo_locations_id'), table_name='geo_locations')
    op.drop_table('geo_locations')
    # ### end Alembic commands ###
