"""empty message

Revision ID: 01d149d925d2
Revises: 0dcce6564b44
Create Date: 2024-11-23 20:15:22.008597

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvecto_rs.sqlalchemy import VECTOR
from pgvecto_rs.types import IndexOption, Hnsw

# revision identifiers, used by Alembic.
revision: str = '01d149d925d2'
down_revision: Union[str, None] = '0dcce6564b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unique_faces',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('centroid', VECTOR(512), nullable=False),
                    sa.Column('user_provided_label', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.add_column('face_boxes',
                  sa.Column('unique_face_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'face_boxes', 'unique_faces', ['unique_face_id'],
                          ['id'])

    op.create_index(
        "centroid_index",
        "unique_faces",
        ["centroid"],
        postgresql_using="vectors",
        postgresql_with={
            "options": f"$${IndexOption(index=Hnsw()).dumps()}$$"
        },
        postgresql_ops={"centroid": "vector_l2_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("centroid_index", table_name="unique_faces")
    op.drop_constraint(None, 'face_boxes', type_='foreignkey')
    op.drop_column('face_boxes', 'unique_face_id')
    op.drop_table('unique_faces')
    # ### end Alembic commands ###
