"""empty message

Revision ID: 0dcce6564b44
Revises: fba277c9e6a6
Create Date: 2024-11-21 23:26:35.986515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvecto_rs.sqlalchemy import VECTOR
from pgvecto_rs.types import IndexOption, Hnsw


# revision identifiers, used by Alembic.
revision: str = '0dcce6564b44'
down_revision: Union[str, None] = 'fba277c9e6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visual_information', 'caption',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visual_information', 'caption',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
