"""change

Revision ID: 492117b96b2f
Revises: 4b48f67ad672
Create Date: 2024-10-27 23:20:15.829696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '492117b96b2f'
down_revision: Union[str, None] = '4b48f67ad672'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('images', 'datetime_utc',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint('images_relative_path_key', 'images', type_='unique')
    op.create_index(op.f('ix_images_datetime_local'), 'images', ['datetime_local'], unique=False)
    op.create_index(op.f('ix_images_datetime_utc'), 'images', ['datetime_utc'], unique=False)
    op.create_index(op.f('ix_images_relative_path'), 'images', ['relative_path'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_relative_path'), table_name='images')
    op.drop_index(op.f('ix_images_datetime_utc'), table_name='images')
    op.drop_index(op.f('ix_images_datetime_local'), table_name='images')
    op.create_unique_constraint('images_relative_path_key', 'images', ['relative_path'])
    op.alter_column('images', 'datetime_utc',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###
