"""change

Revision ID: 71d1e8ff741b
Revises: 492117b96b2f
Create Date: 2024-10-28 21:32:58.285015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71d1e8ff741b'
down_revision: Union[str, None] = '492117b96b2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('is_motion_photo', sa.Boolean(), nullable=False))
    op.add_column('images', sa.Column('is_hdr', sa.Boolean(), nullable=False))
    op.add_column('images', sa.Column('is_night_sight', sa.Boolean(), nullable=False))
    op.add_column('images', sa.Column('is_selfie', sa.Boolean(), nullable=False))
    op.add_column('images', sa.Column('is_panorama', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'is_panorama')
    op.drop_column('images', 'is_selfie')
    op.drop_column('images', 'is_night_sight')
    op.drop_column('images', 'is_hdr')
    op.drop_column('images', 'is_motion_photo')
    # ### end Alembic commands ###
