"""empty message

Revision ID: 79701391bf14
Revises: 7ef1704795f9
Create Date: 2025-01-21 20:34:34.794175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvecto_rs.sqlalchemy import VECTOR
from pgvecto_rs.types import IndexOption, Hnsw
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79701391bf14'
down_revision: Union[str, None] = '7ef1704795f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('is_360', sa.Boolean(), nullable=False))
    op.add_column('images', sa.Column('is_burst', sa.Boolean(), nullable=False))
    op.add_column('images', sa.Column('is_timelapse', sa.Boolean(), nullable=False))
    op.add_column('images', sa.Column('is_slowmotion', sa.Boolean(), nullable=False))
    op.add_column('images', sa.Column('png', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_index('ix_images_id', table_name='images')
    op.drop_column('images', 'is_selfie')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('is_selfie', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index('ix_images_id', 'images', ['id'], unique=False)
    op.drop_column('images', 'png')
    op.drop_column('images', 'is_slowmotion')
    op.drop_column('images', 'is_timelapse')
    op.drop_column('images', 'is_burst')
    op.drop_column('images', 'is_360')
    # ### end Alembic commands ###
