"""empty message

Revision ID: 7ef1704795f9
Revises: a503fbc1fb69
Create Date: 2025-01-14 21:11:20.005202

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ef1704795f9"
down_revision: Union[str, None] = "a503fbc1fb69"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("visual_information", sa.Column("measured_sharpness", sa.Float(), nullable=True))
    op.add_column("visual_information", sa.Column("measured_noise", sa.Integer(), nullable=True))
    op.add_column("visual_information", sa.Column("measured_brightness", sa.Float(), nullable=True))
    op.add_column("visual_information", sa.Column("measured_contrast", sa.Float(), nullable=True))
    op.add_column("visual_information", sa.Column("measured_clipping", sa.Float(), nullable=True))
    op.add_column("visual_information", sa.Column("measured_dynamic_range", sa.Float(), nullable=True))
    op.add_column("visual_information", sa.Column("quality_score", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("visual_information", "quality_score")
    op.drop_column("visual_information", "measured_dynamic_range")
    op.drop_column("visual_information", "measured_clipping")
    op.drop_column("visual_information", "measured_contrast")
    op.drop_column("visual_information", "measured_brightness")
    op.drop_column("visual_information", "measured_noise")
    op.drop_column("visual_information", "measured_sharpness")
    # ### end Alembic commands ###
