"""empty message

Revision ID: 8da031102402
Revises: 17658c670031
Create Date: 2024-11-17 21:09:05.129490

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8da031102402'
down_revision: Union[str, None] = '17658c670031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visual_information',
                  sa.Column('caption', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visual_information', 'caption')
    # ### end Alembic commands ###
