"""empty message

Revision ID: a503fbc1fb69
Revises: 79565462b99b
Create Date: 2024-12-14 18:18:06.368073

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a503fbc1fb69"
down_revision: str | None = "79565462b99b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_datetime_local_utc", "images", ["datetime_local", "datetime_utc"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_datetime_local_utc", table_name="images")
    # ### end Alembic commands ###
