"""empty message

Revision ID: a76fc3f9b482
Revises: 79701391bf14
Create Date: 2025-02-02 22:36:03.163580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvecto_rs.sqlalchemy import VECTOR
from pgvecto_rs.types import IndexOption, Hnsw
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a76fc3f9b482'
down_revision: Union[str, None] = '79701391bf14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visual_information', sa.Column('themes', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.add_column('visual_information', sa.Column('prominent_colors', sa.ARRAY(sa.String()), nullable=False))
    op.add_column('visual_information', sa.Column('average_hue', sa.Float(), nullable=False))
    op.add_column('visual_information', sa.Column('average_saturation', sa.Float(), nullable=False))
    op.add_column('visual_information', sa.Column('average_lightness', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visual_information', 'average_lightness')
    op.drop_column('visual_information', 'average_saturation')
    op.drop_column('visual_information', 'average_hue')
    op.drop_column('visual_information', 'prominent_colors')
    op.drop_column('visual_information', 'themes')
    # ### end Alembic commands ###
