"""change

Revision ID: ad9a9b9fbc2b
Revises: 35f1a28f50b5
Create Date: 2024-10-12 22:27:53.675928

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad9a9b9fbc2b"
down_revision: Union[str, None] = "35f1a28f50b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("process_timings")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "process_timings",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("time_ns", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("iterations", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("id", name="process_timings_pkey"),
    )
    # ### end Alembic commands ###
