"""empty message

Revision ID: b21bdf97abf7
Revises: ded1d117ef4e
Create Date: 2024-11-17 01:44:54.697380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvecto_rs.sqlalchemy import VECTOR
from pgvecto_rs.types import IndexOption, Hnsw


# revision identifiers, used by Alembic.
revision: str = 'b21bdf97abf7'
down_revision: Union[str, None] = 'ded1d117ef4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visual_information', 'ocr_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visual_information', 'ocr_text',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
