"""empty message

Revision ID: ded1d117ef4e
Revises: 1cb865e2147a
Create Date: 2024-11-17 01:40:35.882044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvecto_rs.sqlalchemy import VECTOR
from pgvecto_rs.types import IndexOption, Hnsw


# revision identifiers, used by Alembic.
revision: str = 'ded1d117ef4e'
down_revision: Union[str, None] = '1cb865e2147a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visual_information', sa.Column('ocr_text', sa.Text(), nullable=False))
    op.drop_column('visual_information', 'detected_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visual_information', sa.Column('detected_text', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('visual_information', 'ocr_text')
    # ### end Alembic commands ###
