"""change

Revision ID: f86b1be6f097
Revises: f77dd4864b37
Create Date: 2024-10-12 17:15:48.684558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86b1be6f097'
down_revision: Union[str, None] = 'f77dd4864b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('size_bytes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'size_bytes')
    # ### end Alembic commands ###
