"""empty message

Revision ID: fba277c9e6a6
Revises: 8da031102402
Create Date: 2024-11-21 23:17:50.169320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvecto_rs.sqlalchemy import VECTOR
from pgvecto_rs.types import IndexOption, Hnsw


# revision identifiers, used by Alembic.
revision: str = 'fba277c9e6a6'
down_revision: Union[str, None] = '8da031102402'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('object_boxes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('visual_information_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['visual_information_id'], ['visual_information.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('ocr_boxes', 'confidence',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ocr_boxes', 'confidence',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_table('object_boxes')
    # ### end Alembic commands ###
